arrowParens: avoid
bracketSpacing: false
# endOfLine: lf
# htmlWhitespaceSensitivity: css
insertPragma: false
# parser: babel
printWidth: 1200
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: true
plugins:
  - svelte
svelteSortOrder: options-scripts-markup-styles
svelteStrictMode: false
# svelteBracketNewLine: false
svelteAllowShorthand: true
svelteIndentScriptAndStyle: true
