#!/bin/bash

npx tiged lagden/boilerplate-bin/files#main bin --force
npx tiged lagden/boilerplate-envs/files#main .conf --force
# npx tiged lagden/boilerplate-eslint/files/backend#main . --force
npx tiged lagden/boilerplate-docker-nodejs/files#main . --force
cp .conf/base.back.sh .conf/base.sh
cp .conf/development.back.sh .conf/development.sh
rm .conf/base.*.sh .conf/development.*.sh

exit 0
