name: Node.js CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize
        run: |
          npx tiged lagden/boilerplate-bin/files#main bin --force;
          npx tiged lagden/boilerplate-eslint/files/frontend#main . --force;
          npx tiged lagden/boilerplate-envs/files#main . --force;

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: bin/local/start -b

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
