name: Node.js CI

on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Initialize
        run: |
          npx tiged lagden/boilerplate-bin/files#main bin --force
          npx tiged lagden/boilerplate-envs/files#main .conf --force
          cp .conf/base.front.sh .conf/base.sh
          rm .conf/base.*.sh

      - name: Install dependencies
        run: pnpm i

      - name: Run build
        run: bin/local/start -bi -e production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
